package view;

/**
 *
 * @author Andreas
 */
public class AlleAvtalerPanel extends javax.swing.JPanel {

    /**
     * Creates new form AlleAvtalerPanel
     */
    public AlleAvtalerPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        alleAvtalerScrollPane = new javax.swing.JScrollPane();
        alleAvtalerList = new javax.swing.JList();
        tittelLabel = new javax.swing.JLabel();
        lukkButton = new javax.swing.JButton();
        visButton = new javax.swing.JButton();
        mineAvtalerButton = new javax.swing.JButton();
        mineMoterButton = new javax.swing.JButton();
        tidLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(320, 240));
        setLayout(new java.awt.GridBagLayout());

        alleAvtalerList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        alleAvtalerList.setPreferredSize(new java.awt.Dimension(280, 120));
        alleAvtalerScrollPane.setViewportView(alleAvtalerList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        add(alleAvtalerScrollPane, gridBagConstraints);

        tittelLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tittelLabel.setText("Alle Avtaler og Møter for:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        add(tittelLabel, gridBagConstraints);

        lukkButton.setText("Lukk");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        add(lukkButton, gridBagConstraints);

        visButton.setText("Vis");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        add(visButton, gridBagConstraints);

        mineAvtalerButton.setText("Mine Avtaler");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        add(mineAvtalerButton, gridBagConstraints);

        mineMoterButton.setText("Mine Møter");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        add(mineMoterButton, gridBagConstraints);

        tidLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(tidLabel, new java.awt.GridBagConstraints());
    }// </editor-fold>
    // Variables declaration - do not modify
    private javax.swing.JList alleAvtalerList;
    private javax.swing.JScrollPane alleAvtalerScrollPane;
    private javax.swing.JButton lukkButton;
    private javax.swing.JButton mineAvtalerButton;
    private javax.swing.JButton mineMoterButton;
    private javax.swing.JLabel tidLabel;
    private javax.swing.JLabel tittelLabel;
    private javax.swing.JButton visButton;
    // End of variables declaration
}
