/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AvtalePanel.java
 *
 * Created on 13.mar.2012, 16:40:17
 */
package view;

import java.util.ArrayList;
import java.util.Calendar;

import javax.swing.DefaultComboBoxModel;

import model.Date;
import model.Rom;

import controller.Controller;

/**
 *
 * @author Torbein
 */
public class AvtalePanel extends javax.swing.JPanel {
	ArrayList<Integer> maander;
	ArrayList<Integer> aar;
	ArrayList<Integer> dager;
	ArrayList<Integer> timer;
	ArrayList<Integer> minutter;
	Controller cont;
	Date date;
	
	/** Creates new form AvtalePanel */
	public AvtalePanel(Controller cont) {
		date = new Date();
		this.cont = cont;	
		addItemsToCheckBox();
		initComponents();
		setMoteRomCombobox();
		stedTekstFelt.setEditable(true);
		stedRadioKnapp.setSelected(true);
		moteRomComboBox.setEnabled(false);
		setRealeDate();
	}
	
	private void setRealeDate(){
		maanedComboBox.setSelectedItem(date.getMaaned());
		aarComboBox.setSelectedItem(date.getAar());
		dagComboBox.setSelectedItem(date.getDag());
	}
	/**
	 * Addes days, years and months to the different JComboBoxes.
	 */
	public void addItemsToCheckBox() {
		aar = new ArrayList<Integer>();
		maander = new ArrayList<Integer>();
		dager = new ArrayList<Integer>();
		timer = new ArrayList<Integer>();
		minutter = new ArrayList<Integer>();
		int k = 0;
		for (int i = 1990; i < 2100; i++) {
			aar.add(i);
		}
		for (int i = 1; i < 13; i++) {
			maander.add(i);
		}
		for (int i = 1; i < 32; i++) {
			dager.add(i);
		}
		for (int i = 0; i < 24; i++) {
			timer.add(i);
		}
		for (int i = 0; i < 60; i=i+5) {
			minutter.add(i);
		}
	}

	/**
	 * Adds the available rooms to the moteRomComboBox.
	 */
	public void setMoteRomCombobox(){
		moteRomComboBox.setModel(new DefaultComboBoxModel(cont.getMoteRom().toArray()));
	}

	/**
	 * Checks if the day that is selected in the dagComboBox is compatible with the chosen month. 
	 */
	public void verifyDayValidity(){
		int selectedMonth = Integer.parseInt(maanedComboBox.getSelectedItem().toString());
		int daysInMonth = date.getDaysInMonth(selectedMonth);
		int year = Integer.parseInt(aarComboBox.getSelectedItem().toString());
		dager.clear();
		if(date.isLeapYear(year) && selectedMonth == 2){
			daysInMonth = 29;
		}
		for (int i = 1; i < daysInMonth+1; i++) { 
			dager.add(i);
		}
		dagComboBox.setModel(new javax.swing.DefaultComboBoxModel(dager.toArray())); 
	}
	
	/**
	 * Sets the titel of the page.
	 * @param label
	 */
	protected void setAvtaleLabel(String label){
		avtaleLabel.setText(label);
	}
	
	public String getTittelField(){
		return tittelTekstFelt.getText();
	}
	public String getBeskrivelse()
	{
		return beskrivelseTekstOmraade.getText();
	}
	
	public int getDay()
	{
		return Integer.parseInt(dagComboBox.getSelectedItem().toString());
	}
	
	public int getMonth()
	{
		return Integer.parseInt(maanedComboBox.getSelectedItem().toString());
	}
	
	public int getYear()
	{
		return Integer.parseInt(aarComboBox.getSelectedItem().toString());
	}
	
	public int getStartTime()
	{
		return Integer.parseInt(startTimerComboBox.getSelectedItem().toString());
	}
	public int getStartMinutt()
	{
		return Integer.parseInt(startMinutterComboBox.getSelectedItem().toString());
	}
	
	public int getSluttTimer()
	{
		return Integer.parseInt(sluttTimerComboBox.getSelectedItem().toString());
	}
	public int getSluttMinutter()
	{
		return Integer.parseInt(sluttMinutterComboBox.getSelectedItem().toString());
	}
	public String getSted()
	{
		return stedTekstFelt.getText();
	}
	
	public Rom getMoterom()
	{
		return (Rom) moteRomComboBox.getSelectedItem();
	}
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		buttonGroup1 = new javax.swing.ButtonGroup();
		avtaleLabel = new javax.swing.JLabel();
		tittelLabel = new javax.swing.JLabel();
		beskrivelseLabel = new javax.swing.JLabel();
		datoLabel = new javax.swing.JLabel();
		startTidLabel = new javax.swing.JLabel();
		sluttTidLabel = new javax.swing.JLabel();
		stedLabel = new javax.swing.JLabel();
		moteRomLabel = new javax.swing.JLabel();
		tittelTekstFelt = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		beskrivelseTekstOmraade = new javax.swing.JTextArea();
		dagComboBox = new javax.swing.JComboBox();
		maanedComboBox = new javax.swing.JComboBox();
		aarComboBox = new javax.swing.JComboBox();
		startTimerComboBox = new javax.swing.JComboBox();
		startMinutterComboBox = new javax.swing.JComboBox();
		sluttTimerComboBox = new javax.swing.JComboBox();
		sluttMinutterComboBox = new javax.swing.JComboBox();
		stedRadioKnapp = new javax.swing.JRadioButton();
		moteRadioKnapp = new javax.swing.JRadioButton();
		stedTekstFelt = new javax.swing.JTextField();
		moteRomComboBox = new javax.swing.JComboBox();
		tilbakeKnapp = new javax.swing.JButton();
		lagreKnapp = new javax.swing.JButton();

		//setPreferredSize(new java.awt.Dimension(640, 480));
		setLayout(new java.awt.GridBagLayout());

		avtaleLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		avtaleLabel.setText("Avtale");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
		add(avtaleLabel, gridBagConstraints);

		tittelLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		tittelLabel.setText("Tittel");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		gridBagConstraints.insets = new java.awt.Insets(12, 13, 0, 1);
		add(tittelLabel, gridBagConstraints);

		beskrivelseLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		beskrivelseLabel.setText("Beskrivelse");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
		gridBagConstraints.insets = new java.awt.Insets(12, 13, 0, 4);
		add(beskrivelseLabel, gridBagConstraints);

		datoLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		datoLabel.setText("Dato");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		gridBagConstraints.insets = new java.awt.Insets(12, 13, 0, 1);
		add(datoLabel, gridBagConstraints);

		startTidLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		startTidLabel.setText("Start tid");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		gridBagConstraints.insets = new java.awt.Insets(12, 13, 0, 1);
		add(startTidLabel, gridBagConstraints);

		sluttTidLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		sluttTidLabel.setText("Slutt tid");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 5;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		gridBagConstraints.insets = new java.awt.Insets(12, 13, 0, 1);
		add(sluttTidLabel, gridBagConstraints);

		stedLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		stedLabel.setText("Sted");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 6;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		gridBagConstraints.insets = new java.awt.Insets(12, 13, 0, 1);
		add(stedLabel, gridBagConstraints);

		moteRomLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
		moteRomLabel.setText("M�terom");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 7;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		gridBagConstraints.insets = new java.awt.Insets(12, 13, 0, 1);
		add(moteRomLabel, gridBagConstraints);

		tittelTekstFelt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				tittelTekstFeltActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.gridwidth = 4;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 12);
		add(tittelTekstFelt, gridBagConstraints);

		beskrivelseTekstOmraade.setColumns(20);
		beskrivelseTekstOmraade.setRows(5);
		jScrollPane1.setViewportView(beskrivelseTekstOmraade);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.gridwidth = 4;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 12);
		add(jScrollPane1, gridBagConstraints);

		dagComboBox.setModel(new javax.swing.DefaultComboBoxModel(dager.toArray()));
		dagComboBox.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				dagComboBoxActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.ipadx = 17;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 8);
		add(dagComboBox, gridBagConstraints);

		maanedComboBox.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				maanedComboBoxActionPerformed(evt);
			}
		});
		maanedComboBox.setModel(new javax.swing.DefaultComboBoxModel(maander.toArray()));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.ipadx = 48;
		gridBagConstraints.insets = new java.awt.Insets(12, 5, 0, 11);
		add(maanedComboBox, gridBagConstraints);
		
		aarComboBox.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				aarComboBoxActionPerformed(evt);
			}
		});
		aarComboBox.setModel(new javax.swing.DefaultComboBoxModel(aar.toArray()));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 3;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.ipadx = 17;
		gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 21);
		add(aarComboBox, gridBagConstraints);

		startTimerComboBox.setModel(new javax.swing.DefaultComboBoxModel(timer.toArray()));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.ipadx = 17;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 8);
		add(startTimerComboBox, gridBagConstraints);

		startMinutterComboBox.setModel(new javax.swing.DefaultComboBoxModel(minutter.toArray()));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.ipadx = 17;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		gridBagConstraints.insets = new java.awt.Insets(12, 5, 0, 11);
		add(startMinutterComboBox, gridBagConstraints);

		sluttTimerComboBox.setModel(new javax.swing.DefaultComboBoxModel(timer.toArray()));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 5;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.ipadx = 17;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 8);
		add(sluttTimerComboBox, gridBagConstraints);

		sluttMinutterComboBox.setModel(new javax.swing.DefaultComboBoxModel(minutter.toArray()));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 5;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.ipadx = 17;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		gridBagConstraints.insets = new java.awt.Insets(12, 5, 0, 11);
		add(sluttMinutterComboBox, gridBagConstraints);

		buttonGroup1.add(stedRadioKnapp);
		stedRadioKnapp.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				stedRadioKnappActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 6;
		gridBagConstraints.ipadx = 2;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		gridBagConstraints.weightx = 0.2;
		gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 0);
		add(stedRadioKnapp, gridBagConstraints);

		buttonGroup1.add(moteRadioKnapp);
		moteRadioKnapp.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				moteRadioKnappActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 7;
		gridBagConstraints.ipadx = 2;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		gridBagConstraints.weightx = 0.2;
		gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 0);
		add(moteRadioKnapp, gridBagConstraints);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 6;
		gridBagConstraints.gridwidth = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(12, 29, 0, 12);
		add(stedTekstFelt, gridBagConstraints);

		moteRomComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 7;
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.ipadx = 17;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		gridBagConstraints.insets = new java.awt.Insets(12, 30, 0, 0);
		add(moteRomComboBox, gridBagConstraints);

		tilbakeKnapp.setText("Tilbake");
		tilbakeKnapp.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				tilbakeKnappActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 11;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.insets = new java.awt.Insets(12, 13, 10, 1);
		add(tilbakeKnapp, gridBagConstraints);

		lagreKnapp.setText("Lagre");
		lagreKnapp.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				lagreKnappActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 3;
		gridBagConstraints.gridy = 11;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.insets = new java.awt.Insets(12, 0, 10, 12);
		add(lagreKnapp, gridBagConstraints);
	}// </editor-fold>

	private void tittelTekstFeltActionPerformed(java.awt.event.ActionEvent evt) {
		cont.actionPerformed(evt);
	}

	private void dagComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
		cont.actionPerformed(evt);
	}

	private void maanedComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
		verifyDayValidity();
	}
	
	private void aarComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
		verifyDayValidity();
	}

	private void moteRadioKnappActionPerformed(java.awt.event.ActionEvent evt) {
		moteRomComboBox.setEnabled(true);
		stedTekstFelt.setEditable(false);
	}

	private void stedRadioKnappActionPerformed(java.awt.event.ActionEvent evt) {
		stedTekstFelt.setEditable(true);
		moteRomComboBox.setEnabled(false);
	}

	private void tilbakeKnappActionPerformed(java.awt.event.ActionEvent evt) {
		cont.actionPerformed(evt);
	}

	private void lagreKnappActionPerformed(java.awt.event.ActionEvent evt) {
		cont.actionPerformed(evt);
	}

	// Variables declaration - do not modify
	protected java.awt.GridBagConstraints gridBagConstraints;
	private javax.swing.JComboBox aarComboBox;
	private javax.swing.JLabel avtaleLabel;
	private javax.swing.JLabel beskrivelseLabel;
	private javax.swing.JTextArea beskrivelseTekstOmraade;
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JComboBox dagComboBox;
	private javax.swing.JLabel datoLabel;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JButton lagreKnapp;
	private javax.swing.JComboBox maanedComboBox;
	private javax.swing.JRadioButton moteRadioKnapp;
	private javax.swing.JComboBox moteRomComboBox;
	private javax.swing.JLabel moteRomLabel;
	private javax.swing.JComboBox sluttMinutterComboBox;
	private javax.swing.JLabel sluttTidLabel;
	private javax.swing.JComboBox sluttTimerComboBox;
	private javax.swing.JComboBox startMinutterComboBox;
	private javax.swing.JLabel startTidLabel;
	private javax.swing.JComboBox startTimerComboBox;
	private javax.swing.JLabel stedLabel;
	private javax.swing.JRadioButton stedRadioKnapp;
	private javax.swing.JTextField stedTekstFelt;
	private javax.swing.JButton tilbakeKnapp;
	private javax.swing.JLabel tittelLabel;
	private javax.swing.JTextField tittelTekstFelt;
	// End of variables declaration
}
