package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import controller.Controller;

/**
 *
 * @author Andreas
 */
public class InboxPanel extends javax.swing.JPanel {

	//TODO Add following code to Controller:
	/*
	 * else if(currentGUI instanceof InboxPanel ) {
			if(e.getActionCommand().equals("Vis Melding")) {
				
			}
		}
		
	 */
	
	private void addToController(){
		
	}
	
    /**
     * Creates new form Inbox
     */
	Controller cont;
    public InboxPanel(Controller cont) {
        this.cont = cont;
    	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        visMeldingKnapp = new javax.swing.JButton();
        slettKnapp = new javax.swing.JButton();
        tilbakeKnapp = new javax.swing.JButton();
        nyMeldingKnapp = new javax.swing.JButton();
        inboxScrollPane = new javax.swing.JScrollPane();
        inboxListe = new javax.swing.JList();
        tittelLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(640, 480));
        setLayout(new java.awt.GridBagLayout());

        visMeldingKnapp.setText("Vis Melding");
        visMeldingKnapp.addActionListener(cont);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        add(visMeldingKnapp, gridBagConstraints);

        slettKnapp.setText("Slett");
        slettKnapp.addActionListener(cont);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        add(slettKnapp, gridBagConstraints);

        tilbakeKnapp.setText("Tilbake");
        tilbakeKnapp.addActionListener(cont);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        add(tilbakeKnapp, gridBagConstraints);

        nyMeldingKnapp.setText("Ny Melding");
        nyMeldingKnapp.addActionListener(cont);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        add(nyMeldingKnapp, gridBagConstraints);

        inboxScrollPane.setPreferredSize(new java.awt.Dimension(500, 375));

        inboxListe.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        inboxListe.setPreferredSize(new java.awt.Dimension(450, 350));
        inboxScrollPane.setViewportView(inboxListe);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        add(inboxScrollPane, gridBagConstraints);

        tittelLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tittelLabel.setText("Inbox:");
        add(tittelLabel, new java.awt.GridBagConstraints());
    }// </editor-fold>
    // Variables declaration - do not modify
    private javax.swing.JList inboxListe;
    private javax.swing.JScrollPane inboxScrollPane;
    private javax.swing.JButton nyMeldingKnapp;
    private javax.swing.JButton slettKnapp;
    private javax.swing.JButton tilbakeKnapp;
    private javax.swing.JLabel tittelLabel;
    private javax.swing.JButton visMeldingKnapp;
    // End of variables declaration
}
