/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Component;
import java.awt.Graphics;
import java.awt.Image;

import javax.swing.Icon;
import javax.swing.ImageIcon;

import controller.Controller;

/**
 *
 * @author Eier
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
	Controller cont;
    public LoginPanel(Controller cont) {
        this.cont = cont;
    	initComponents();
    }
    public String getUser(){
    	return brukerNavnFelt.getText();
    }
    public String getPassword(){
    	
    	return passordFelt.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        brukerNavnLabel = new javax.swing.JLabel();
        passordLabel = new javax.swing.JLabel();
        brukerNavnFelt = new javax.swing.JTextField();
        passordFelt = new javax.swing.JPasswordField();
        loginBilde = new javax.swing.JLabel();
        loggPaKnapp = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());
        
        brukerNavnLabel.setText("Brukernavn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 2;
        add(brukerNavnLabel, gridBagConstraints);

        passordLabel.setText("Passord");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 2;
        add(passordLabel, gridBagConstraints);

        brukerNavnFelt.setText("");
        brukerNavnFelt.setMinimumSize(new java.awt.Dimension(22, 22));
        brukerNavnFelt.setPreferredSize(new java.awt.Dimension(126, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        add(brukerNavnFelt, gridBagConstraints);

        passordFelt.setText("");
        passordFelt.setPreferredSize(new java.awt.Dimension(126, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        add(passordFelt, gridBagConstraints);


        //loginBilde.setIcon(new ImageIcon(getClass().getResource("lock.png")));

        loginBilde.setIcon(new ImageIcon(getClass().getResource("/bilder/lock.png")));
        loginBilde.setIcon(new ImageIcon(getClass().getResource("../bilder/lock.png")));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(loginBilde, gridBagConstraints);

        loggPaKnapp.setText("Logg inn");
        loggPaKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loggPaKnappActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        add(loggPaKnapp, gridBagConstraints);
    }// </editor-fold>

    private void loggPaKnappActionPerformed(java.awt.event.ActionEvent evt) {
        cont.actionPerformed(evt);
    }

    // Variables declaration - do not modify
    private javax.swing.JTextField brukerNavnFelt;
    private javax.swing.JLabel brukerNavnLabel;
    private javax.swing.JButton loggPaKnapp;
    private javax.swing.JLabel loginBilde;
    private javax.swing.JPasswordField passordFelt;
    private javax.swing.JLabel passordLabel;
    // End of variables declaration
}
