package view;

import java.util.ArrayList;

import javax.swing.AbstractListModel;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import model.Ansatt;
import model.Avtale;
import model.Mote;

import controller.Controller;

/**
 *
 * @author Andreas
 */
public class MineAvtalerPanel extends javax.swing.JPanel {

    /**
     * Creates new form MineAvtalerPanel
     */
	private Controller cont;
	
    public MineAvtalerPanel(Controller cont) {
        this.cont = cont;
    	initComponents();
    	setMineAvtalerListe(cont.getAppointments());
    }
    
    public void setMineAvtalerListe(ArrayList<Avtale> items){
    	listModel.clear();
    	for (Avtale avtale : items) {
    		listModel.addElement(avtale);
		}
    }
    
    /**
     * This method shows the information of the selected meeting on the bottom part of the screen.
     */
    private void showInfoOnSelectedAppointments(){
    	Avtale avtale = (Avtale) mineAvtalerListe.getSelectedValue();
    	if(avtale!=null){
	    	beskrivelseTextArea.setText(avtale.getBeskrivelse());
	    	fraLabel.setText(avtale.getStartTime()+":"+avtale.getSluttMinutt());
	    	tilLabel.setText(avtale.getSluttTime()+":"+avtale.getSluttMinutt());
	    	stedLabel.setText(avtale.getSted());
    	}
    	return;
    }
    
    public Avtale removeSelectedAppointments(){
    	Avtale avtale = (Avtale) mineAvtalerListe.getSelectedValue();
    	return avtale;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        nyAvtaleKnapp = new javax.swing.JButton();
        tilbakeKnapp = new javax.swing.JButton();
        visAvtaleKnapp = new javax.swing.JButton();
        redigerAvtaleKnapp = new javax.swing.JButton();
        fjernAvtaleKnapp = new javax.swing.JButton();
        mineAvtalerScrollPane = new javax.swing.JScrollPane();
        mineAvtalerListe = new javax.swing.JList();
        tittelLabel = new javax.swing.JLabel();
        avtaleInfoPanel = new javax.swing.JPanel();
        beskrivelseLabel = new javax.swing.JLabel();
        beskrivelseScrollPane = new javax.swing.JScrollPane();
        beskrivelseTextArea = new javax.swing.JTextArea();
        fraLabel = new javax.swing.JLabel();
        tilLabel = new javax.swing.JLabel();
        stedLabel = new javax.swing.JLabel();
        fraVerdiLabel = new javax.swing.JLabel();
        tilVerdiLabel = new javax.swing.JLabel();
        stedVerdiLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(640, 480));
        setLayout(new java.awt.GridBagLayout());

        nyAvtaleKnapp.setText("Ny Avtale");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(nyAvtaleKnapp, gridBagConstraints);

        tilbakeKnapp.setText("Tilbake");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(tilbakeKnapp, gridBagConstraints);

        visAvtaleKnapp.setText("Vis Avtale");
        visAvtaleKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visAvtaleKnappActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(visAvtaleKnapp, gridBagConstraints);

        redigerAvtaleKnapp.setText("Rediger Avtale");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        add(redigerAvtaleKnapp, gridBagConstraints);

        fjernAvtaleKnapp.setText("Fjern Avtale");
        fjernAvtaleKnapp.addActionListener(cont);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        add(fjernAvtaleKnapp, gridBagConstraints);

        mineAvtalerScrollPane.setPreferredSize(new java.awt.Dimension(475, 125));

        //Endret til defaultListModel
        listModel = new DefaultListModel();
        mineAvtalerListe.addListSelectionListener(new ListSelectionListener() {
			
			@Override
			public void valueChanged(ListSelectionEvent e) {
				visMineAvtaleListListener(e);
			}
		});
        mineAvtalerListe.setModel(listModel);
        mineAvtalerScrollPane.setViewportView(mineAvtalerListe);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        add(mineAvtalerScrollPane, gridBagConstraints);

        tittelLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tittelLabel.setText("Mine avtaler:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(tittelLabel, gridBagConstraints);

        avtaleInfoPanel.setLayout(new java.awt.GridBagLayout());

        beskrivelseLabel.setText("Beskrivelse:");
        avtaleInfoPanel.add(beskrivelseLabel, new java.awt.GridBagConstraints());

        beskrivelseScrollPane.setPreferredSize(new java.awt.Dimension(250, 100));

        beskrivelseTextArea.setColumns(20);
        beskrivelseTextArea.setEditable(false);
        beskrivelseTextArea.setRows(5);
        beskrivelseScrollPane.setViewportView(beskrivelseTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        avtaleInfoPanel.add(beskrivelseScrollPane, gridBagConstraints);

        fraLabel.setText("Fra:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        avtaleInfoPanel.add(fraLabel, gridBagConstraints);

        tilLabel.setText("Til:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        avtaleInfoPanel.add(tilLabel, gridBagConstraints);

        stedLabel.setText("Sted:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        avtaleInfoPanel.add(stedLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        avtaleInfoPanel.add(fraVerdiLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        avtaleInfoPanel.add(tilVerdiLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        avtaleInfoPanel.add(stedVerdiLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        add(avtaleInfoPanel, gridBagConstraints);
    }// </editor-fold>

    private void visAvtaleKnappActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    
    private void visMineAvtaleListListener(ListSelectionEvent e) {
    	showInfoOnSelectedAppointments();
	}

    // Variables declaration - do not modify
    private javax.swing.JPanel avtaleInfoPanel;
    private javax.swing.JLabel beskrivelseLabel;
    private javax.swing.JScrollPane beskrivelseScrollPane;
    private javax.swing.JTextArea beskrivelseTextArea;
    private javax.swing.JButton fjernAvtaleKnapp;
    private javax.swing.JLabel fraLabel;
    private javax.swing.JLabel fraVerdiLabel;
    private javax.swing.JList mineAvtalerListe;
    private javax.swing.JScrollPane mineAvtalerScrollPane;
    private javax.swing.JButton nyAvtaleKnapp;
    private javax.swing.JButton redigerAvtaleKnapp;
    private javax.swing.JLabel stedLabel;
    private javax.swing.JLabel stedVerdiLabel;
    private javax.swing.JLabel tilLabel;
    private javax.swing.JLabel tilVerdiLabel;
    private javax.swing.JButton tilbakeKnapp;
    private javax.swing.JLabel tittelLabel;
    private javax.swing.JButton visAvtaleKnapp;
    private DefaultListModel listModel;
    // End of variables declaration
}
