package view;

import java.awt.Dimension;
import javax.swing.JFrame;
import controller.Controller;

/**
 *
 * @author Andreas
 */
public class MotePanel extends AvtalePanel {

    /**
     * Creates new form MotePanel
     */
    public MotePanel(Controller cont) {
    	super(cont);
        initComponents();
        super.setAvtaleLabel("M�te:");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        allePersonerScrollPane = new javax.swing.JScrollPane();
        allePersonerList = new javax.swing.JList();
        fjernButton = new javax.swing.JButton();
        leggTilButton = new javax.swing.JButton();
        deltakereScrollPane = new javax.swing.JScrollPane();
        deltakereList = new javax.swing.JList();
        allePersonerLabel = new javax.swing.JLabel();
        deltakereLabel = new javax.swing.JLabel();

        //AllePersoner List
        allePersonerList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        allePersonerList.setPreferredSize(new java.awt.Dimension(150, 100));
        allePersonerScrollPane.setViewportView(allePersonerList);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.gridwidth = 2;
        add(allePersonerScrollPane, gridBagConstraints);

        //Fjern Button
        fjernButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bilder/arrow22-left.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        add(fjernButton, gridBagConstraints);

        //LeggTil Button
        leggTilButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bilder/arrow22-right.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        add(leggTilButton, gridBagConstraints);

        //Deltakere List
        deltakereList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        deltakereList.setPreferredSize(new java.awt.Dimension(150, 100));
        deltakereScrollPane.setViewportView(deltakereList);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.gridwidth = 2;
        add(deltakereScrollPane, gridBagConstraints);

        //AllePersoner Label
        allePersonerLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        allePersonerLabel.setText("Alle Personer:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        add(allePersonerLabel, gridBagConstraints);

        //Deltakere Label
        deltakereLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deltakereLabel.setText("Deltakere:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        add(deltakereLabel, gridBagConstraints);
    }// </editor-fold>
    
    // Variables declaration - do not modify
    private javax.swing.JLabel allePersonerLabel;
    private javax.swing.JList allePersonerList;
    private javax.swing.JScrollPane allePersonerScrollPane;
    private javax.swing.JLabel deltakereLabel;
    private javax.swing.JList deltakereList;
    private javax.swing.JScrollPane deltakereScrollPane;
    private javax.swing.JButton fjernButton;
    private javax.swing.JButton leggTilButton;
    // End of variables declaration
}
