package view;

/**
 *
 * @author Andreas
 */
public class UlesteMeldingerPanel extends javax.swing.JPanel {

    /**
     * Creates new form MiniInboxPanel
     */
    public UlesteMeldingerPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        ulesteMeldingerScrollPane = new javax.swing.JScrollPane();
        ulesteMeldingerList = new javax.swing.JList();
        tittelLabel = new javax.swing.JLabel();
        lukkButton = new javax.swing.JButton();
        visMeldingButton = new javax.swing.JButton();
        inboxButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(320, 240));
        setLayout(new java.awt.GridBagLayout());

        ulesteMeldingerList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        ulesteMeldingerList.setPreferredSize(new java.awt.Dimension(280, 120));
        ulesteMeldingerScrollPane.setViewportView(ulesteMeldingerList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        add(ulesteMeldingerScrollPane, gridBagConstraints);

        tittelLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tittelLabel.setText("Uleste Meldinger");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        add(tittelLabel, gridBagConstraints);

        lukkButton.setText("Lukk");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(lukkButton, gridBagConstraints);

        visMeldingButton.setText("Vis Melding");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        add(visMeldingButton, gridBagConstraints);

        inboxButton.setText("Inbox");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        add(inboxButton, gridBagConstraints);
    }// </editor-fold>
    
    
    // Variables declaration - do not modify
    private javax.swing.JButton inboxButton;
    private javax.swing.JButton lukkButton;
    private javax.swing.JLabel tittelLabel;
    private javax.swing.JList ulesteMeldingerList;
    private javax.swing.JScrollPane ulesteMeldingerScrollPane;
    private javax.swing.JButton visMeldingButton;
    // End of variables declaration
}
