package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JDialog;

import model.Melding;
import controller.Controller;

/**
 *
 * @author Andreas
 */
public class VisMeldingPanel extends javax.swing.JPanel {

    /**
     * Creates new form VisMeldingPanel
     */  
	private Controller cont;
	private JDialog dialog;
	private Melding melding;
	//cutomActionListener is made so 
	private ActionListener customActionListener = new ActionListener() {
		
		@Override
		public void actionPerformed(ActionEvent e) {
			e.setSource(this);
			cont.actionPerformed(e);
		}
	};
	
    public VisMeldingPanel(Controller cont, Melding melding) {
        initComponents();
        this.cont = cont;
        this.melding = melding;
        dialog = cont.getDialog();
    }
    
    public void nyMelding() {
    	senderTextField.setText(melding.getSender().getBrukerNavn());
    	beskjedTextArea.setEditable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        senderLabel = new javax.swing.JLabel();
        senderTextField = new javax.swing.JTextField();
        beskjedScrollPane = new javax.swing.JScrollPane();
        beskjedTextArea = new javax.swing.JTextArea();
        lukkKnapp = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(320, 240));
        setLayout(new java.awt.GridBagLayout());

        senderLabel.setText("Sender:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        add(senderLabel, gridBagConstraints);

        senderTextField.setEditable(false);
        senderTextField.setPreferredSize(new java.awt.Dimension(200, 20));
        senderTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senderTextFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        add(senderTextField, gridBagConstraints);

        beskjedScrollPane.setPreferredSize(new java.awt.Dimension(253, 100));

        beskjedTextArea.setColumns(20);
        beskjedTextArea.setEditable(false);
        beskjedTextArea.setRows(5);
        beskjedScrollPane.setViewportView(beskjedTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(beskjedScrollPane, gridBagConstraints);

        lukkKnapp.setText("Lukk");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(lukkKnapp, gridBagConstraints);
    }// </editor-fold>

    private void senderTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    // Variables declaration
    protected java.awt.GridBagConstraints gridBagConstraints;
    private javax.swing.JScrollPane beskjedScrollPane;
    private javax.swing.JTextArea beskjedTextArea;
    private javax.swing.JButton lukkKnapp;
    private javax.swing.JLabel senderLabel;
    private javax.swing.JTextField senderTextField;
    // End of variables declaration
}
